version: '2.1'
services:
  appium:
    image: appium/appium
    restart: on-failure
    privileged: true
    environment:
      TZ: /usr/share/zoneinfo/Europe/Madrid
    volumes:
      - /dev/bus/usb:/dev/bus/usb
  robot:
    image: oprietop/robotframework
    working_dir: /robot
    depends_on:
      - appium
    environment:
      TZ: /usr/share/zoneinfo/Europe/Madrid
    volumes:
      - ./robot:/robot
      - ./out:/out
    command: >
      sh -c "sleep 5s; robot -d /out /robot"
